#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Auto TOP-UP, queued behind the live E1 run (run_e1_2gpu.sh).
#
# Goal: bring ta/te/or up to the SAME 5-condition battery as en/hi/bn, WITHOUT
# redoing the deploy/eval_log generations E1 already produced. The condition-aware
# --resume in 09_cue_battery_grid.py reads each per-language CSV, sees deploy+eval_log
# already present, and runs ONLY the 3 new conditions (neutral_log, eval_explicit,
# eval_metadata), appending them. en/hi/bn already have all 5 → not touched here.
#
# Scheduling (captures the ~2h GPU3-finishes-early overlap):
#   GPU3 lane: wait GPU3 shard done → top-up `ta` → (wait GPU2 shard done) → top-up `te`
#   GPU2 lane: wait GPU2 shard done → top-up `or`
# `te`'s base CSV is produced by the GPU2 shard, so the GPU3 lane waits for the GPU2
# shard before touching `te` — guarantees no two processes ever write the same
# per-language CSV (ta⇒GPU3 only, te⇒GPU3 only after GPU2 done, or⇒GPU2 only).
#
# Completion signal: each E1 shard prints "[GPUx] SHARD DONE" to its log at the end.
# No sudo, venv-only, all writes under mech_interp/.
# ─────────────────────────────────────────────────────────────────────────────
set +e
cd /home/sibayan_mitra_2024/mech_interp || exit 1
PY=/home/sibayan_mitra_2024/mech_interp/.venv/bin/python
LOG3=results/behavioral/e1_gpu3.log
LOG2=results/behavioral/e1_gpu2.log
TLOG=results/behavioral/topup.log
POLL=300   # seconds between completion checks (keeps log noise low)

wait_for_shard () {  # $1 = log file, $2 = label
  until grep -q "SHARD DONE" "$1" 2>/dev/null; do sleep "$POLL"; done
  echo "[topup] detected SHARD DONE in $2 ($1) $(date)"
}

echo "=== TOPUP WATCHER START $(date) (pid $$) ===" | tee -a "$TLOG"
echo "[topup] waiting for E1 shards; polling every ${POLL}s" | tee -a "$TLOG"

# ── GPU3 lane: ta (base ready when GPU3 shard done), then te (base from GPU2 shard) ──
(
  wait_for_shard "$LOG3" "GPU3"
  echo "[topup/GPU3] start ta $(date)"
  CUDA_VISIBLE_DEVICES=3 $PY scripts/09_cue_battery_grid.py --lang ta --resume
  echo "[topup/GPU3] done ta exit=$? $(date)"
  # te's deploy/eval_log base is generated by the GPU2 shard — wait before touching it
  wait_for_shard "$LOG2" "GPU2 (for te base)"
  echo "[topup/GPU3] start te $(date)"
  CUDA_VISIBLE_DEVICES=3 $PY scripts/09_cue_battery_grid.py --lang te --resume
  echo "[topup/GPU3] done te exit=$? $(date)"
  echo "[topup/GPU3] LANE DONE $(date)"
) >> "$TLOG" 2>&1 &
T3=$!

# ── GPU2 lane: or (base ready when GPU2 shard done) ──
(
  wait_for_shard "$LOG2" "GPU2"
  echo "[topup/GPU2] start or $(date)"
  CUDA_VISIBLE_DEVICES=2 $PY scripts/09_cue_battery_grid.py --lang or --resume
  echo "[topup/GPU2] done or exit=$? $(date)"
  echo "[topup/GPU2] LANE DONE $(date)"
) >> "$TLOG" 2>&1 &
T2=$!

wait $T3 $T2

# ── final authoritative merge (now includes the topped-up ta/te/or 5-condition data) ──
$PY -c "
import pandas as pd, glob
fs=[f for f in sorted(glob.glob('results/behavioral/cue_battery_*.csv')) if not f.endswith('cue_battery_grid.csv')]
parts=[pd.read_csv(f) for f in fs]
m=pd.concat(parts, ignore_index=True)
m.to_csv('results/behavioral/cue_battery_grid.csv', index=False)
print('merged', len(m), 'rows from', len(fs), 'lang files ->', sorted(m.lang.unique()))
print('per (lang,condition) counts:')
print(m.groupby(['lang','condition']).size().to_string())
print('per (lang,condition) refusal mean:')
print(m.groupby(['lang','condition'])['refusal'].mean().round(2).to_string())
" >> "$TLOG" 2>&1

echo "=== TOPUP WATCHER DONE $(date) ===" >> "$TLOG"
